<table class="admin__control-table">
        <tr>
            <th>Timestamp</th>
            <th>Status</th>
            <th>Message</th>
            <th>Read More</th>
        </tr>
        <?php $counter = 0 ?>
        <?php $type = $block->getType() ?>
        <?php foreach($block->getLogs() as $log) : ?>
        <?php $counter++ ?>
        <tr>
            <td><?php echo $log['timestamp'] ?></td>
            <td><?php echo $log['status'] ?></td>
            <td><?php echo mb_strimwidth($log['message'], 0, 80, "..") ?></td>
            <td><button id="button-modal-<?= $counter ?>-<?= $type ?>">
                    <span><?= $block->escapeHtml(__('Click me')) ?></span>
                </button>

                <div id="modal-<?= $counter ?>-<?= $type ?>">
                    <div class="modal-<?= $counter ?>-<?= $type ?>-body-content">
                        <h3>Message:</h3>
                        <p><?php echo nl2br($log['message']) ?></p>
                        <br />

                        <?php if($log['requestBody']) : ?>
                            <h3>Request Info:</h3>
                            <p><strong>Request Headers:</strong></p>
                                <p style="margin-left: 40px;"><?php echo nl2br($log['requestHeaders']) ?></p>
                            <p><strong>Request Method:</strong> <?php echo nl2br($log['requestMethod']) ?></p>
                            <p><strong>Request Uri:</strong> <?php echo nl2br($log['requestUri']) ?></p>
                            <p><strong>Request Body:</strong></p>
                                <p style="margin-left: 40px"><?php echo htmlspecialchars($log['requestBody'], ENT_QUOTES) ?></p>
                            <br />
                        <?php endif; ?>

                        <?php if($log['responseBody']) : ?>
                            <h3>Response Info:</h3>
                            <p><strong>Response Headers:</strong></p>
                                <p style="margin-left: 40px;"><?php echo nl2br($log['responseHeaders']) ?></p>
                            <p><strong>Response Answer:</strong> <?php echo nl2br($log['responseReasonPhrase']) ?></p>
                            <p><strong>Response Status Code:</strong> <?php echo nl2br($log['responseStatusCode']) ?></p>
                            <p><strong>Response Body:</strong></p>
                                <p style="margin-left: 40px"><?php echo htmlspecialchars($log['responseBody'], ENT_QUOTES) ?></p>
                        <?php endif; ?>
                    </div>
                </div>

                <script type="text/javascript">
                    require([
                        "jquery",
                        "Magento_Ui/js/modal/modal"
                    ],function($, modal) {

                        var options = {
                            type: 'slide',
                            responsive: true,
                            title: 'Log with timestamp <?php echo $log['timestamp'] ?>',
                            buttons: [{
                                text: $.mage.__('Ok'),
                                class: '',
                                click: function () {
                                    this.closeModal();
                                }
                            }]
                        };

                        var popup = modal(options, $('#modal-<?= $counter ?>-<?= $type ?>'));
                        $("#button-modal-<?= $counter ?>-<?= $type ?>").click(function() {
                            $('#modal-<?= $counter ?>-<?= $type ?>').modal('openModal');
                        });
                    });
                </script></td>
        </tr>

        <?php endforeach; ?>
</table>




